### ISSUE TITLE
Some words don't immediately change when switching locale

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-distance#84]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1009, the words "meters" ,"degrees" and "units" don't change to the new locale until a value is changed (The only exception is in the third scene of the Explore screen. For some reason "meters" changes right away there.).

**Steps to reproduce**
On the Explore Screen (first scene):
1. Place the person and house in the play area
2. Change locale--ex. Swahili--all of the words in the Distance Statement will have changed except for "meters"
       
<img width="487" alt="Screenshot 2023-12-08 at 8 55 45 AM" src="https://github.com/phetsims/number-line-distance/assets/87318828/d4eb90de-5b80-4fd8-a8a6-2969165ba674">

3. Move the person or the house--the word "meters" in now in Swahili

<img width="487" alt="Screenshot 2023-12-08 at 8 56 06 AM" src="https://github.com/phetsims/number-line-distance/assets/87318828/7cc49eda-2b94-46ec-bdf6-46e78f306541">

4. Change locale back to English--the word 'meters' is still in Swahili until you move the person or house

<img width="487" alt="Screenshot 2023-12-08 at 8 56 26 AM" src="https://github.com/phetsims/number-line-distance/assets/87318828/7cee7827-a8ce-40ce-b56a-9a97bf68a0cd">

Follow similar steps for the second scene of the Explore Screen and for the Generic Screen. 

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Distance_數線：距離‬
URL: https://phet-dev.colorado.edu/html/number-line-distance/1.1.0-rc.2/phet/number-line-distance_all_phet.html
Version: 1.1.0-rc.2 2023-12-01 00:37:11 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15
Language: en-US
Window: 1403x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
I also did not see this on main, but was able to reproduce in the RC.

**Comment by Nancy-Salpepi** [comment]
@marlitas it is definitely fixed on main! Maybe it was fixed in a commit for https://github.com/phetsims/number-line-integers/issues/113#issuecomment-1850927717?

**Comment by marlitas** [comment]
I checked that commit and it was not related. I even reverted to see and no luck... I'm not finding the commit right now, but I'll keep looking and pull some help in on the best way to track it down.

**Comment by marlitas** [comment]
@zepumph and @samreid were amazing and helped me figure this out. We are still unsure why, but apparently the bug was only appearing in built versions (but still not a built version on main). We committed fixes that we think improved the code overall, not just for this bug and the next step will be to cherry-pick when things are ready.

**Comment by samreid** [comment]
I wonder if built vs unbuilt somehow has a different listener order.

**Comment by marlitas** [comment]
Cherry picked for https://github.com/phetsims/qa/issues/1018. Feel free to close if all looks well.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.4. Closing.
